version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            curl -fsSl https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node -v
            npm -v
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v1

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v1

            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend:v1

            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy $DOCKER_USERNAME/udagram-reverseproxy:v1

            echo "-----------All images successfully built-----------"

            echo "-----------login in to hub--------------"

            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            echo "----------Pushing images to dockerhub----------"

            docker push $DOCKER_USERNAME/udagram-api-feed:v1
            docker push $DOCKER_USERNAME/udagram-api-user:v1
            docker push $DOCKER_USERNAME/udagram-frontend:v1
            docker push $DOCKER_USERNAME/udagram-reverseproxy:v1

workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]
